### ISSUE TITLE
Cannot read properties of undefined (reading 'run') in development mode (App.Develop)

### ISSUE THREAD

**Issue by cazzzt** [lemonmade/quilt#245]
<img width="1358" alt="Снимок экрана 2022-04-11 в 13 05 53" src="https://user-images.githubusercontent.com/8135074/162716116-a61930b2-493b-47af-8082-a631f225afd5.png">

"@quilted/craft": "^0.1.95"

**Comment by lemonmade** [comment]
Can you check if this is still an issue for you?

**Comment by cazzzt** [comment]
After the update this problem is no more. Thanks!

**Comment by cazzzt** [comment]
After the update this problem is no more. Thanks!
