### ISSUE TITLE
Errors after build

### ISSUE THREAD

**Issue by cazzzt** [lemonmade/quilt#325]
<img width="1241" alt="Снимок экрана 2022-05-24 в 15 42 00" src="https://user-images.githubusercontent.com/8135074/170037228-6a458d54-c3ca-48c1-8172-da1c16de5eb2.png">

PORT=3000 node ./app/build/server/index.js

**Comment by lemonmade** [comment]
Can you share a small project that replicates the error?

**Comment by cazzzt** [comment]
If i use react-query or SWR i get this error. This error does not occur in development mode.

**Comment by lemonmade** [comment]
Sorry, I am no longer able to replicate these errors with swr or react-query. This may have been fixed in one of the more recent versions.
