### ISSUE TITLE
React not aliased to @quilted/react when using NPM

### ISSUE THREAD

**Issue by cazzzt** [lemonmade/quilt#374]
<img width="1440" alt="Снимок экрана 2022-07-12 в 15 38 44" src="https://user-images.githubusercontent.com/8135074/178491741-4303f836-13bc-4fee-97aa-7e9556648450.png">

**Comment by lemonmade** [comment]
Do you have an example app that reproduces the problem? I think I have seen similar issues when react/ preact are installed multiple times with different versions, but I can't be sure without seeing the error in an actual project.

**Comment by lemonmade** [comment]
Thanks for the reproduction! This appears to be an issue with NPM not installing `@quilted/react` in place of `react`, as I would expect it to do with the way that dependency is declared. I wasn't able to fix it locally, unfortunately. I'll have to try again to determine if it's a bug in NPM's dependency installation, or if I am using this feature wrong.

The dependency is resolved correctly for both Yarn and PNPM, so you can either use one of those, or add additional custom aliases to Rollup, Jest, and Vite that manually do the work of mapping `react` => `@quilted/react`. Sorry for the inconvenience ☹️

**Comment by lemonmade** [comment]
Per https://stackoverflow.com/questions/56134857/how-to-install-npm-package-under-alias-or-different-name, this was added in npm 6.9 I was able to use this myself with nom 8.5. I think the existing setup should work with most reasonably recent versions of NPM, so I am going to close this one.
