### ISSUE TITLE
react-testing | unable to import matchers

### ISSUE THREAD

**Issue by afonsograca** [lemonmade/quilt#701]
👋 
I was trying to update my RN project to version the latest version of `react-testing`, but once I do I lose access to the custom matchers provided by the package.

Looking at the documentation, it seems like nothing changed, I should simply need to import
```typescript
import '@quilted/react-testing/matchers';
```
after Jest's setup and the matchers should be available.

Looking at the changes from 0.5.32 to 0.6.0, the `index.ts` file in the matchers folder was removed, which explains why the import stopped working.

My question is, was this an accidental removal or is there a new way to import the matchers that is not documented?

Cheers

**Comment by lemonmade** [comment]
Thanks @afonsograca, you were getting caught by a broken set of type definitions for this package. Fixed in https://github.com/lemonmade/quilt/commit/f4b568ea97e5b1d2fb77223bf85548b4c979d035, and released in `@quilted/react-testing@0.6.6`.
